__import:
  - project/services.yml
  - ../data/data.yml

# routing
bfy_adapter.sf2_routing.routing:    '&project/routing.yml'
bfy_app.routing.action_name_of_404: 'project.controller.default:page404'

bfy_plugin.template_router.templates_dirs:
  - dir:             '%app.dir.root%/view'
    prefix_uri:      'auto'
    prefix_template: 'auto'

# doctrine
bfy_adapter.doctrine.configuration_paths:
  - '%app.dir.root%/src/Project/Entity'

bfy_adapter.doctrine.db_parameters:
  driver:   'pdo_mysql'
  charset:  'UTF8'
  user:     ''
  password: ''
  dbname:   ''

# templates
bfy_adapter.twig.asset.version:   1
bfy_adapter.twig.template_paths:
  - '%app.dir.root%/view'

bfy_adapter.twig.configuration:
  cache: '%app.dir.root%/var/twig'
  debug: true

services:

  twig.butterfly.extension:
    class: 'ButterflyAddition\TwigExtension'
    arguments: [%bfy_adapter.twig.asset.version%, @bfy_adapter.sf2_routing.url_generator]
    tags: 'bfy_adapter.twig.extensions'
